### ISSUE TITLE
Too hard expression

### ISSUE THREAD

**Issue by vitiaaap29** [Grindan/knockoutjs-treeview-task#4]
https://github.com/Grindan/knockoutjs-treeview-task/blob/42d4bba7ecd0507b942b51d49558824b3d5cef18/src/index.html#L97

I think that it's reasonable to move the expression from markup to js. The logic isn't obvious.
It's **low** priority.

**Comment by Grindan** [comment]
All similar expressions were removed to js (there was added new ko.computed property).
